branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "semantic-release-cargo"
    - "allFeatures": true
      "check": true
      "checkArgs": []
      "publishArgs": []
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - "assets":
        - "package.json"
        - "CHANGELOG.md"
        - "README.md"
        - "Cargo.toml"
      "message": "chore(release): ${nextRelease.version} 🚀 [skip ci]\n\n${nextRelease.notes}"
