name: Build, Test, & Release 🚀
on:
  push:
    branches:
      - "main"
  pull_request_target:
    types: [opened, synchronize, edited]
env:
  REF: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
concurrency: ${{ github.ref }}-${{ github.event_name }}-${{ github.event.pull_request.head.ref }}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: ${{ env.REF }}
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: swatinem/rust-cache@v2
        name: setup cache
        with:
          prefix-key: "${{ hashFiles('Cargo.toml') }}"
      - name: run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: ${{ env.REF }}
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: swatinem/rust-cache@v2
        name: setup cache
        with:
          prefix-key: "${{ hashFiles('Cargo.toml') }}"
      - name: run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    permissions:
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: ${{ env.REF }}
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: swatinem/rust-cache@v2
        name: setup cache
        with:
          prefix-key: "${{ matrix.os }}-${{ hashFiles('Cargo.toml') }}"
      - name: aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::507109231688:role/automation-gha
          aws-region: eu-west-2
      - name: gcp
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.STORAGE_CREDENTIALS }}
      - name: run cargo test
        shell: bash
        run: cargo test
  tests-complete:
    runs-on: ubuntu-latest
    needs: [test, lint, check]
    if: ${{ github.event_name != 'push' }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          ref: ${{ env.REF }}
      - name: approve-dependabot
        if: ${{ github.actor == 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: |
          gh pr review --approve || true
          gh pr merge --auto --rebase || true
  publish:
    runs-on: ubuntu-latest
    needs: [test, lint, check]
    if: github.ref_name == github.event.repository.default_branch && !contains( github.event.head_commit.message, 'skip ci' )
    timeout-minutes: 20
    env:
      GH_TOKEN: ${{ secrets.GH_PA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: swatinem/rust-cache@v2
        name: setup cache
        with:
          prefix-key: "${{ hashFiles('Cargo.toml') }}"
      - name: npm install
        run: npm ci
      - name: publish
        env:
          GH_TOKEN: ${{ secrets.MY_PA_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          npm run release
